resolver: lts-8.21

packages:
  - .
  - location: ../vulkan-api
    extra-dep: true
  - location:
      git: https://github.com/achirkin/GLFW-b
      commit: 1c34109deeb5ed465df783830c2ecf54a8daa873
    extra-dep: true
  - location:
      git: https://github.com/bsl/bindings-GLFW
      commit: 0e0d7272ce9caeb4461acc607b6536e84d048a4a
    extra-dep: true
