resolver: lts-14.15

extra-deps:
  - ../vulkan-api

packages:
  - .

nix:
  enable: false
  packages: [vulkan-loader, libGL, xorg.libX11, xorg.libXinerama,  xorg.libXcursor, xorg.libXrandr, xorg.libXi, mesa, xorg.libXxf86vm, glslang]
