resolver: lts-14.15

ghc-options:
  vulkan-api:    -O2
  GLFW-b:        -O2
  bindings-GLFW: -O2

flags:
  vulkan-api:
    useNativeFFI-1-0: true
    useNativeFFI-1-1: false
    useUnsafeFFIDefault: true

extra-deps:
  - constraints-deriving-1.0.4.0
  - dimensions-2.0.0.0
  - easytensor-2.0.1.0
  - easytensor-vulkan-2.0.1.0
  - wavefront-0.7.1.3
  - ../vulkan-api

packages:
  - .

nix:
  enable: false
  packages: [zlib, vulkan-loader, libGL, xorg.libX11, xorg.libXinerama,  xorg.libXcursor, xorg.libXrandr, xorg.libXi, mesa, xorg.libXxf86vm, glslang]
